---
services:
  app84:
    build:
      context: .
      args:
        PHP_VERSION: "8.4.0RC3"
    environment:
      PHP_IDE_CONFIG: 'serverName=icanboogie-autoconfig'
    volumes:
      - .:/app:delegated
      - ~/.composer:/root/.composer:delegated
    working_dir: /app
